config/routes.rb
Businesshound::Application.routes.draw do  
  controller :admin do
    get 'admin' => :index
  end
  
  resources :factories, only: :show do
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
  end
      
  resources :stores, only: :show do
    resources :bulk_stocks, only: :new do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form        
      end
    end
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
    resources :journal_entries, except: :show
    resource :cash_entries
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
    
  resources :companies
  
  namespace :admin do
    resources :products do
      collection do
        put :sort
      end
    end
    resources :stores, :factories
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'sessions#new'
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  attr_accessible :amount, :message, :store_id, :kind, :occured_on
  validates :kind, inclusion: { in: %w(debit credit), message: "%{value} is not a valid type of transaction" }
  validates_presence_of :message, :amount, :store_id, :occured_on

  belongs_to :store
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
	before_filter :load_store

	def index
    @journal_entries = @store.journal_entries.where(occured_on: @occured_on)
	end

	def new
		@journal_entry = @store.journal_entries.build(occured_on: @occured_on)
	end

	def create
		@occured_on = params[:journal_entry][:occured_on]
		@journal_entry = @store.journal_entries.build(params[:journal_entry])
		flash[:failure] = "Entry could not be saved." unless @journal_entry.save
	end

	def destroy
		@journal_entry = JournalEntry.find(params[:id])
		@journal_entry.destroy
	end

	private

	def load_store
    @occured_on = date
		@store = Store.find(params[:store_id])
	end
end

app/views/journal_entries/_form.html.erb
<%= form_for(@journal_entry, url: store_journal_entries_path(@store), remote: true, html: {class: 'form-inline', style: 'float:right'}) do |f| %>
    <%= f.text_field :message, class: 'input-xlarge', placeholder: 'Message' %>
    <div class="input-prepend" align="left">
    	<span class="add-on"><%= current_company.currency %></span><%= f.text_field :amount, class: 'input-small' %>
		</div>
    <%= f.select :kind, {"Debit"=>"debit", "Credit"=>"credit"}, {}, class: 'input-small' %>&nbsp;
    <%= f.hidden_field :occured_on %>
    <%= f.submit "Add", class: "btn btn-success" %>
<% end %>

app/views/journal_entries/_journal_entry.html.erb
<tr id='<%= "journal_entry_#{journal_entry.id}" %>'>
  <td><%= journal_entry.message %></td>
  <td><%= "#{current_user.company.currency} #{journal_entry.amount}" %></td>
  <td><%= journal_entry.kind.capitalize %></td>
  <td><%= link_to '<i class="icon-trash"></i>'.html_safe, store_journal_entry_path(@store, journal_entry), class: "trash", title: "Delete", method: :delete, remote: true,confirm: "Are you sure?" %></td>
</tr>

app/views/journal_entries/create.js.erb
$('.alert').remove();
<% if @journal_entry.errors.any? %>
	$('#journal_entry_content').prepend('<%= j render("layouts/flash", flash: flash) %>');
<% else %>
	$('#new_journal_entry').remove();
	$('#new-entry').show();
	$('#journal_entries tbody').append('<%= j render(@journal_entry) %>').children(':last').hide().fadeIn();
<% end %>

app/views/journal_entries/destroy.js.erb
$('#journal_entry_<%= @journal_entry.id %>').fadeOut();

app/views/journal_entries/index.html.erb
<%= render 'stores/sidebar', store: @store %>

<div id="center" class="span9 shadow-box">
  <div class="span2">
    <div class="input-append date" id="datepicker" data-date="<%= @occured_on %>" data-date-format="dd-mm-yyyy">
      <input size="16" type="text" value="<%= @occured_on %>" class="input-small" readonly>
      <span class="add-on"><i class="icon-calendar"></i></span>
    </div>
  </div>

  <div id="journal_entry_content" class="span10">
    <%= link_to 'New Entry', new_store_journal_entry_path(@store, date: @occured_on), remote: true, id: 'new-entry', class: 'btn btn-primary', style: 'float:right;' %><br/><br/><br/>

    <table id="journal_entries" align="center" class="table table-bordered">
      <thead>
        <tr>
          <th>Message</th>
          <th>Amount</th>
          <th>Type</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @journal_entries.each do |entry| %>
          <%= render entry %>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker().on('changeDate', function(e){
      var occured_on = formatDate(e.date);
      document.location = '<%= store_journal_entries_path(@store) %>?date=' + occured_on;
    });
  });
</script>

app/views/journal_entries/new.js.erb
$('#new-entry').hide().after('<%= j render "form" %>');