config/routes.rb
Businesshound::Application.routes.draw do  
  controller :admin do
    get 'admin' => :index
  end
  
  resources :factories, only: :show do
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
  end
      
  resources :stores, only: :show do
    resources :bulk_stocks, only: :new do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form        
      end
    end
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
    resources :journal_entries, except: :show
    resource :cash_entries
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
    
  resources :companies
  
  namespace :admin do
    resources :products do
      collection do
        put :sort
      end
    end
    resources :stores, :factories
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'sessions#new'
end

app/views/admin/_sidebar.html.erb
<div class="span3">
  <div class="well" style="padding: 8px 0;">
    <ul id="admin-sidebar" class="nav nav-list">
      <li class="nav-header">Company Actions</li>
			<li><%= link_to '<i class="icon-list"></i> Summary'.html_safe, admin_path %></li>
			<li><%= link_to '<i class="icon-barcode"></i> Products'.html_safe, admin_products_path %></li>
			<li><%= link_to '<i class="icon-shopping-cart"></i> Stores'.html_safe, admin_stores_path %></li>
			<li><%= link_to '<i class="icon-home"></i> Factories'.html_safe, admin_factories_path %></li>
			<!-- <li class="nav-header">Admin Functions</li>
      <li><a href="#"><i class="icon-user"></i>Profile</a></li>
      <li><a href="#"><i class="icon-wrench"></i>Settings</a></li> -->
      <li class="divider"></li>
			<li><%= link_to '<i class="icon-off"></i> Log Out'.html_safe, logout_url, method: :delete %></li>
    </ul>
  </div> <!-- /well -->
</div>

app/views/admin/index.html.erb
<%= render 'admin/sidebar' %>

<div id="center" class="span9 shadow-box">
  <div class="row-fluid">
    <div class="span2">
      <div class="input-append date" id="datepicker" data-date="<%= @date %>" data-date-format="dd-mm-yyyy">
        <input size="16" type="text" value="<%= @date %>" class="input-small" readonly>
        <span class="add-on"><i class="icon-calendar"></i></span>
      </div>
    </div>
    <div class="span10">
      <div class="dropdown">
        <button class="btn dropdown-toggle sr-only" type="button" id="stores-dropdown" data-toggle="dropdown">
          <%= @store.name %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <% @stores.each do |store| %>
            <li <% if store.id == @store.id %>class="active"<% end %>><a href="<%= admin_path(store_id: store.id, date: date) %>"><%= store.name %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <%= render 'layouts/flash', flash: flash %>
      <%= render 'layouts/summary', store: @store, date: @date %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker().on('changeDate', function(e){
      var date = formatDate(e.date);
      document.location = '<%= admin_path(store_id: @store.id) %>&date=' + date;
    });
  });
</script>