config/routes.rb
Businesshound::Application.routes.draw do  
  controller :admin do
    get 'admin' => :index
  end
  
  resources :factories, only: :show do
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
  end
      
  resources :stores, only: :show do
    resources :bulk_stocks, only: :new do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form        
      end
    end
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
    resources :journal_entries, except: :show
    resource :cash_entries
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
    
  resources :companies
  
  namespace :admin do
    resources :products do
      collection do
        put :sort
      end
    end
    resources :stores, :factories
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'sessions#new'
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :name, presence: { message: "Store name is required" }
  validates :name, uniqueness: { scope: :company_id, case_sensitive: false, message: "%{value} already exists" }
  validates_presence_of :factories, message: "Select at least one factory that supplies to this store", if: ->(store) { store.company.factories.any? }
  
  belongs_to :company
  belongs_to :manager, class_name: 'User', dependent: :destroy
  has_many :products, through: :company
  has_many :supplies, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :journal_entries, dependent: :destroy
  has_many :cash_entries, dependent: :destroy
  has_and_belongs_to_many :factories

  accepts_nested_attributes_for :stocks, :supplies

  def gets_supplies_by?(factory)
  	factories.include? factory
  end

  def has_entered_stock_on?(date)
    stocks.where(left_on: date).any?
  end

  def has_entered_supplies_on?(supplied_on)
    supplies.where(store_id: id, supplied_on: supplied_on, factory_id: nil).any?
  end

  def find_stock_by_attributes(left_on, product_id)
    stock = stocks.where(product_id: product_id, left_on: left_on).pop
    stock.present? ? stock : false
  end

  def fetch_stocks(left_on)
    stocks = []
    products.each do |product|
      stocks << if stock = find_stock_by_attributes(left_on, product.id)
        stock
      else
        self.stocks.create(product_id: product.id, quantity: 0, left_on: left_on)
      end
    end
    stocks
  end

  def find_supply_by_attributes(supplied_on, product_id)
    supply = supplies.where(store_id: id, product_id: product_id, supplied_on: supplied_on, factory_id: nil).pop
    supply.present? ? supply : false
  end

  def fetch_supplies(store_id, supplied_on)
    supplies = []
    products.traded.each do |product|
      supplies << if supply = find_supply_by_attributes(supplied_on, product.id)
        supply
      else
        self.supplies.create(product_id: product.id, quantity: 0, supplied_on: supplied_on)
      end
    end
    supplies
  end

  def has_entered_denominations_on?(date)
    cash_entries.find_by_made_on(date).present?
  end

  def goods_supplied_on?(date)
    supplies.where(supplied_on: date).any?
  end

  def stocks_entered_on?(date)
    stocks.where(left_on: date).any?
  end

  def products_eligible_for_supply_entry
    products.traded
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::AdminController  
  def index
    @stores = Store.where(company_id: current_company.id).order :name
  end

  def new
    @store = Store.new
    @user = User.new
  end
  
  def create
    params[:store][:factories].collect! { |id| Factory.find_by_id(id) } unless params[:store][:factories].nil?

    @store = current_company.stores.build params[:store]
    @user = @store.build_manager params[:user].merge(user_type: "store", company: current_company)

    if @store.valid? & @user.valid?
      @store.save(validate: false)
      @user.save(validate: false)
      redirect_to admin_stores_path, flash: {success: "#{@store.name} was successfully added."}
    else
      render action: "new"
    end
  end
  
  def edit
    @store = Store.find(params[:id])
  end
  
  def update
    if params[:store][:factories].nil?
      params[:store][:factories] = []
    else
      params[:store][:factories].collect! { |id| Factory.find_by_id(id) }
    end

    @store = Store.find(params[:id])

    if @store.update_attributes(params[:store])
      redirect_to admin_stores_path, flash: {success: "Store was successfully updated."}
    else
      render "edit"  
    end
  end
  
  def destroy
    Store.find(params[:id]).destroy
    flash[:success] = "Store successfully deleted."
    respond_to do |format|
      format.html { redirect_to admin_stores_path }
    end
  end
end

app/controllers/store/stocks_controller.rb
class Store::StocksController < ApplicationController
  before_filter :authorize_user_type, :load_store
  layout false, only: :fetch_form

  def index
    @date = params[:date] || Date.today
  end

  def new
    @left_on = Time.now.strftime("%Y-%m-%d")
    @stocks = @store.products.map { |product| @store.stocks.build(product: product) }
  end

  def create
    @stocks = []
    @left_on = params[:store][:left_on]

    @store.products.each.with_index do |product, i|
      @stocks << @store.stocks.build(params[:store][:stocks_attributes][i.to_s].merge(left_on: @left_on))
    end
    
    if @store.save
      redirect_to store_stocks_path, flash: {success: "Left-over stock items were added for #{@store.name}."}
    else
      render 'new'
    end
  end

  def edit
    @left_on = Time.now.strftime("%Y-%m-%d")
    @stocks = @store.fetch_stocks Date.today
  end

  def update
    @stocks = []
    @left_on = params[:store][:left_on]

    Stock.transaction do
      params[:store][:stocks_attributes].values.each do |stock_attributes|
        stock = @store.stocks.where(left_on: @left_on, product_id: stock_attributes[:product_id]).first
        unless stock.update_attributes(quantity: stock_attributes[:quantity])
          @store.errors.clear
          @store.errors.add(:stocks_attributes, "Stocks quantity should be a number")
        end
        @stocks << stock
      end
    end

    unless @store.errors.any?
      redirect_to store_stocks_path, flash: {success: "Left-over stock items were added for #{@store.name}"}
    else
      render 'edit'
    end
  end

  def fetch_form
    @left_on = params[:date]

    @stocks = if @store.has_entered_stock_on?(@left_on)
      @form_options = { url: store_stock_path(@store), method: :put }
      @store.fetch_stocks @left_on
    else
      @form_options = { url: store_stocks_path, method: :post }
      @store.products.map { |product| @store.stocks.build(product: product) }
    end    
  end

  protected

  def authorize_user_type
    render file: 'public/401.html', status: :unauthorized unless logged_in_as_store_manager?
  end

  private

  def load_store
    @store = current_user.store
  end  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @store = Store.find(params[:id])
    @date = date
  end
end

app/helpers/store/stocks_helper.rb
module Store::StocksHelper
	def old_stock(product, store, date)
		stock_by_date product, store, (format_date(date) - 1.day)
	end

	def todays_supplies(product, store, date)
		product.supplies.where(store_id: store.id, supplied_on: format_date(date)).first.quantity
	end

	def left_over_stock(product, store, date)
		stock_by_date product, store, format_date(date)
	end

	def format_date(date)
		date.is_a?(Date) ? date : Date.strptime(date, '%Y-%m-%d')
	end

	def stock_by_date(product, store, date)
		stock = product.stocks.where(store_id: store.id, left_on: date).first
		stock.present? ? stock.quantity : 0
	end
end

app/helpers/stores_helper.rb
module StoresHelper
	def old_stock(product, store, date)
		stock_by_date product, store, (format_date(date) - 1.day)
	end

	def todays_supplies(product, store, date)
		supply = product.supplies.where(store_id: store.id, supplied_on: format_date(date)).first
		supply.present? ? supply.quantity : 0		
	end

	def left_over_stock(product, store, date)
		stock_by_date product, store, format_date(date)
	end

	def format_date(date)
		date.is_a?(Date) ? date : Date.strptime(date, '%d-%m-%Y')
	end

	def stock_by_date(product, store, date)
		stock = product.stocks.where(store_id: store.id, left_on: date).first
		stock.present? ? stock.quantity : 0
	end
end

app/views/admin/stores/edit.html.erb
<div class="span12">
	<div class="shadow-box add-item-box">
	<h2>Edit Store</h2><br />

	<% if @store.errors.any? %>
	  <div class="alert alert-error">
	    <ul>
	    <% @store.errors.each do |field, msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>


	<%= form_for(@store, url: admin_store_path(@store)) do |f| %>	
		<div>
	    <%= f.label :name, "Store Name:" %>
	    <%= f.text_field :name, class: "input-block-level" %>
	  </div>

		<% if current_company.factories.any? %>
			<div>
		    <u><%= label_tag "Select factories which supply to this store" %></u>
				<% current_company.factories.each do |factory| %>
					<div>
						<%= label_tag factory.name.parameterize.underscore,
									check_box_tag("store[factories][]",
										factory.id,
										@store.gets_supplies_by?(factory) ? true : false) + factory.name,
										class: "checkbox" %>
				  </div>
				<% end %>
			</div>
		<% end %>

	  <br /><div>
	    <%= f.submit "Update", class: "btn btn-success btn-large" %>
	  </div>
	<% end %>
	</div>
</div>

app/views/admin/stores/index.html.erb
<%= render 'admin/sidebar' %>

<div id="center" class="span8 shadow-box">
	<%= render 'layouts/flash', flash: flash %>
	
  <% if @stores.any? %>
  	<table class="table table-striped table-hover" width="100%">
      <thead>
        <tr>
          <th>#</th>
          <th width="45%">Store Name</th>
          <th>Description</th>
          <th width="5%"></th>
          <th width="5%"></th>
        </tr>
      </thead>
      <tbody>
  		<% @stores.each.with_index do |store, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= store.name %></td>
          <td><%= "Today's Sale: #{current_user.company.currency}" %></td>
          <td style="text-align:center;"><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_admin_store_path(store), class: "edit", title: "Edit" %></td>
          <td style="text-align:center;"><%= link_to '<i class="icon-trash"></i>'.html_safe, admin_store_path(store), class: "trash", title: "Delete", method: :delete, confirm: "Are you sure?" %></td>
        </tr>
      <% end %>  
      </tbody>
  	</table>
  <% elsif !flash.any? %>
    <div class="alert alert-info">
      <b>No stores!</b> Well, you need to click the plus button on the right to add some.
    </div>
  <% end %>
</div>

<div class="span1">
	<a href="<%= new_admin_store_path %>" id="add-item" title="Add New Store"><%= image_tag "icons/glyphicons_190_circle_plus.png" %></a>
</div>

app/views/admin/stores/new.html.erb
<div class="span12">
	<div id="add-store-box" class="shadow-box add-item-box">
	<h2>Add Store</h2>

	<% if @store.errors.any? or @user.errors.any? %>
	  <div class="alert alert-error">
	    <ul>
	    <% @store.errors.each do |field, msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= form_for(@store, url: admin_stores_path) do |f| %>	
		<div>
	    <%= f.label :name, "Store Name" %>
	    <%= f.text_field :name, class: 'input-xlarge' %>
	  </div>
		<%= fields_for @user do |f| %>
			<div>
		    <%= f.label :fullname, "Manager Name", class: "control-label" %>
		    <%= f.text_field :fullname, class: "input-xlarge" %>
		  </div>
			<div>
		    <%= f.label :email, "Manager Email",class: "control-label" %>
		    <%= f.text_field :email, class: "input-xlarge" %>
		  </div>
			<div>
		    <%= f.label :username, "Username", class: "control-label" %>
		    <%= f.text_field :username, class: "input-xlarge" %>
		  </div>
			<div>
			  <%= f.label :password, class: "control-label" %>
			  <%= f.password_field :password, class: "input-xlarge" %>
			</div>
			<div>
			  <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
			  <%= f.password_field :password_confirmation, class: "input-xlarge" %>
			</div>
		<% end %>

		<% if current_company.factories.any? %>
			<div>
		    <u><%= label_tag "Select factories which supply to this store" %></u>
				<% current_company.factories.each do |factory| %>
					<div>
						<%= label_tag factory.name.parameterize.underscore,
									check_box_tag("store[factories][]",
										factory.id,
										false) + factory.name,
										class: "checkbox" %>
				  </div>
				<% end %>
			</div>
		<% end %>
	  
	  <br/><div>
	    <%= f.submit "Add", class: "btn btn-success btn-large" %>
	  </div>
	<% end %>
	</div>
</div>