config/routes.rb
Businesshound::Application.routes.draw do  
  controller :admin do
    get 'admin' => :index
  end
  
  resources :factories, only: :show do
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
  end
      
  resources :stores, only: :show do
    resources :bulk_stocks, only: :new do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form        
      end
    end
    resources :bulk_supplies, only: [:index, :new] do
      collection do
        post :create
        get :edit
        put :update
        get :fetch_form
      end
    end
    resources :journal_entries, except: :show
    resource :cash_entries
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
    
  resources :companies
  
  namespace :admin do
    resources :products do
      collection do
        put :sort
      end
    end
    resources :stores, :factories
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'sessions#new'
end

app/models/product.rb
class Product < ActiveRecord::Base
	default_scope order(:position)
	scope :produced, where(kind: 'produced')
	scope :traded, where(kind: 'traded')

  validates :name, presence: true, uniqueness: { scope: :company_id, case_sensitive: false, message: "%{value} already exists" }
  validates :price, presence: true, numericality: { greater_than: 0, message: "should be more than 0"}
  validates :kind, inclusion: { in: %w{produced traded}, message: "%{value} is not a valid kind"}

  belongs_to :company
  has_many :supplies, dependent: :destroy
  has_many :stocks, dependent: :destroy
  acts_as_list scope: :company
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  def index
    @products = Product.where(company_id: current_company.id).order :name
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    @product.company_id = current_company.id
    if @product.save
      redirect_to admin_products_path, flash: {success: "#{@product.name} was successfully added."}
    else
      render "new"  
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to admin_products_path, flash: {success: "Product was successfully updated."}
    else
      render "edit"  
    end
  end
  
  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product successfully deleted."
    respond_to do |format|
      format.html { redirect_to admin_products_path }
      format.js
    end
  end

  def sort
    params[:product].each.with_index do |id, i|
      current_company.products.update_all({ position: i + 1 }, { id: id })
    end
    render nothing: true
  end
end

app/views/admin/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="alert alert-error">
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@product, url: @product.new_record? ? admin_products_path : admin_product_path(@product)) do |f| %>	
	<div>
    <%= f.label :name, "Product Name" %>
    <%= f.text_field :name, class: 'input-block-level' %>
  </div>
	<div>
    <%= f.label :price, "Price" %>
    <div id="price-prepend" class="input-prepend" align="left">
    	<span class="add-on"><%= current_company.currency %></span><%= f.text_field :price %>
		</div>
  </div>
  <div>
    <%= f.label :kind, "Type", style: 'margin-top: 10px;' %>
    <%= f.select :kind, {"Produced"=>"produced", "Traded"=>"traded"}, {}, class: 'input-block-level' %>
  </div><br />
  <div>
    <%= f.submit @product.new_record? ? "Add" : "Update", class: "btn btn-success btn-large" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="span12">
	<div class="shadow-box add-item-box">
	<h2>Edit Product</h2><br />

	<%= render 'form' %>
	</div>
</div>

app/views/admin/products/index.html.erb
<%= render 'admin/sidebar' %>

<div id="center" class="span8 shadow-box">
	<%= render 'layouts/flash', flash: flash %>
	
  <% if @products.any? %>
  	<table class="table table-striped table-hover" width="100%">
      <thead>
        <tr>
          <th>Sort</th>
          <th width="25%" style="text-align:center;">Product Image</th>
          <th width="40%">Product Name</th>
          <th>Kind</th>
          <th width="15%">Price</th>
          <th width="5%"></th>
          <th width="5%"></th>
        </tr>
      </thead>
      <tbody id="sortable" data-sort-url="<%= sort_admin_products_path %>">
  		<% @products.each do |product| %>
        <%= content_tag_for :tr, product do %>
          <td><i class="sortable-handle icon-resize-vertical"></i></span></td>
          <td width="25%"  style="text-align:center;"><img /></td>
          <td width="40%" ><%= product.name %></td>
          <td><%= product.kind.capitalize %></td>
          <td width="15%" ><%= "#{current_user.company.currency} #{product.price}" %></td>
          <td width="5%"  style="text-align:center;"><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_admin_product_path(product), class: "edit", title: "Edit" %></td>
          <td width="5%"  style="text-align:center;"><%= link_to '<i class="icon-trash"></i>'.html_safe, admin_product_path(product), class: "trash", title: "Delete", method: :delete, confirm: "Are you sure?" %></td>
        <% end %>
      <% end %>  
      </tbody>
  	</table>
  <% elsif !flash.any? %>
    <div class="alert alert-info">
      <b>No products!</b> Well, you need to click the plus button on the right to add some.
    </div>
  <% end %>
</div>

<div class="span1">
  <a href="<%= new_admin_product_path %>" id="add-item" title="Add New Product"><%= image_tag "icons/glyphicons_190_circle_plus.png" %></a>
</div>

app/views/admin/products/new.html.erb
<div class="span12">
	<div class="shadow-box add-item-box">
	<h2>Add Product</h2><br />

	<%= render 'form' %>
	</div>
</div>